
version: 2

models:
  - name: changesets_raw
    description: "data from changesets parquet files"
    columns:
      - name: id
        description: "changeset id"
        data_tests:
          - unique
          - not_null
        
  - name: changesets_number_per_user
    description: "number of changeset for particular user"
    columns:
      - name: id
        description: "changeset id"
        data_tests:
          - unique
          - not_null

  - name: changesets_by_month_app
    description: "aggregations by month per app (created_by)"

  - name: changesets_by_month_host
    description: "aggregations by month per host"