
version: 2

models:
  - name: changesets_raw
    description: "data from changesets parquet files"
    columns:
      - name: id
        description: "changeset id"
        data_tests:
          - unique
          - not_null
        
  - name: first_user_changeset
    description: "uid and his/her/their first changeset id"
    columns:
      - name: uid
        description: "user id"
        data_tests:
          - unique
          - not_null

  - name: changesets_number_per_user
    description: "uid and his/her/their changeset number ordered by creation date"

  - name: changesets_by_month_app
    description: "aggregations by month per app (created_by)"

  - name: changesets_by_month_host
    description: "aggregations by month per host"