
version: 2

models:
  - name: changesets_filtered_raw
    description: "adjusted data from changesets_filtered.parquet"
    columns:
      - name: id
        description: "changeset id"
        data_tests:
          - unique
          - not_null

  - name: changesets_filtered_by_month_app
    description: "aggregations by month per app (created_by)"
    # columns:
    #   - name: id
    #     description: "The primary key for this table"
    #     data_tests:
    #       - unique
    #       - not_null

  - name: changesets_filtered_by_month_app
    description: "aggregations by month per app (created_by)"